# Site settings
title: Bruno Henrique Barbosa
description: '# egrep -R ''sysadmin|ICT|infosec|stuff'' /bhbarbosa/brain/thoughts'
url: 'https://bhbarbosa.github.io'
baseurl: '/'
google_analytics: 'UA-74608033-1'
disqus_shortname: 'bhbarbosagithubio'

author:
  name: 'Bruno Henrique Barbosa'
  email: bhbarbosa@gmail.com
  twitter_username: bhbarbosa_
  github_username:  bhbarbosa
  linkedin_username:  bhbarbosa

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
paginate: 10
permalink: /:year/:month/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
